dev:
  db:
    host: "localhost"
    port: '5444'
    name: "postgres"
    user: "postgres"
    password: "postgres"
prod:
  db:
    host: "localhost"
    port: '5445'
    name: "postgres"
    user: "postgres"
    password: "postgres"